[build]
functions = "netlify/functions"
command = "npm run build"


[functions]
directory = "functions"

[[redirects]]
  from = "/.netlify/functions/api2"
  to = "/.netlify/functions/api"
  status = 200
  force = true
