[build]
functions = "netlify/functions"
command = "npm run build"


[functions]
directory = "functions"

[[redirects]]
  from = "/api2"
  to = "https://api.clashofclans.com/v1"
  status = 200
  force = true