[build]
functions = "netlify/functions"
command = "npm run build"


[functions]
directory = "functions"

[[redirects]]
  from = ".netlify/functions/api2"
  to = "https://endzone-clan.de"
  status = 200
  force = true