[build]
functions = "functions"

[functions]
node_bundler = "esbuild"
external_node_modules = [
    "express",
    "cors",
    "axios",
    "serverless"
]


[[headers]]
  for = "/*.json"
  [headers.values]
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"

