[build]
functions = "netlify/functions"
command = "nom run build"
publish = "build"

[functions]
directory = "functions"
node_bundler = "esbuild"
external_node_modules = [
    "cors",
    "axios",
    "serverless"
]


