[build]
functions ="src/functions"
publish = "dist"

[functions]
directory = "src/functions"
node_bundler = "esbuild"
external_node_modules = [
    "express",
    "cors",
    "axios",
    "serverless"
]
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
