[build]
functions ="src/functions"


[functions]
directory = "src/functions"
node_bundler = "esbuild"
external_node_modules = [
    "express",
    "cors",
    "axios",
    "serverless"
]
[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"

